/* eslint-disable @typescript-eslint/no-var-requires */
export function formatDate(date: string): string {
    const cdate = new Date(date)
    const options = {
        year: "numeric",
        month: "short",
        day: "numeric",
        hour12: false,
    } as const
    date = cdate.toLocaleDateString("en-us", options)
    return date
}

export function formatBytes(bytes: number, decimals = 2) {
    if (!+bytes) return "0 Bytes"

    const k = 1024
    const dm = decimals < 0 ? 0 : decimals
    const sizes = [
        "Bytes",
        "KiB",
        "MiB",
        "GiB",
        "TiB",
        "PiB",
        "EiB",
        "ZiB",
        "YiB",
    ]

    const i = Math.floor(Math.log(bytes) / Math.log(k))

    return `${parseFloat((bytes / Math.pow(k, i)).toFixed(dm))} ${sizes[i]}`
}

export async function convertImgToBase64(
    url: string,
    outputFormat: string = "image",
): Promise<string> {
    return new Promise((resolve, reject) => {
        const canvas = document.createElement("CANVAS") as HTMLCanvasElement
        const ctx = canvas.getContext("2d")
        const img = new Image()
        img.crossOrigin = "Anonymous"
        img.onload = function () {
            canvas.height = img.height
            canvas.width = img.width
            ctx?.drawImage(img, 0, 0)
            const dataURL = canvas.toDataURL(outputFormat)
            resolve(dataURL)
            canvas.remove() // Clean up the canvas element
        }
        img.onerror = reject
        img.src = url
    })
}

export async function getUniqueImageUrls(
    imageUrls: string[],
): Promise<string[]> {
    const uniqueBase64s = new Set<string>()
    const uniqueUrls: string[] = []

    for (const url of imageUrls) {
        try {
            const base64Img = await convertImgToBase64(url)
            if (!uniqueBase64s.has(base64Img)) {
                uniqueBase64s.add(base64Img)
                uniqueUrls.push(url)
            }
        } catch (error) {
            console.error(`Failed to convert image ${url} to base64`, error)
        }
    }

    return uniqueUrls
}

// MimeTypes
export const appMimeTypes: { [key: string]: string } = {
    "application/andrew-inset": "Andrew Toolkit",
    "application/applixware": "Applixware",
    "application/atom+xml": "Atom Syndication Format",
    "application/atomcat+xml": "Atom Publishing Protocol",
    "application/atomsvc+xml": "Atom Publishing Protocol Service Document",
    "application/ccxml+xml": "Voice Browser Call Control",
    "application/cdmi-capability":
        "Cloud Data Management Interface (CDMI) - Capability",
    "application/cdmi-container":
        "Cloud Data Management Interface (CDMI) - Containe",
    "application/cdmi-domain":
        "Cloud Data Management Interface (CDMI) - Domain",
    "application/cdmi-object":
        "Cloud Data Management Interface (CDMI) - Object",
    "application/cdmi-queue": "Cloud Data Management Interface (CDMI) - Queue",
    "application/cu-seeme": "Cu-SeeMe",
    "application/davmount+xml":
        "Web Distributed Authoring and Versioning (WebDAV) mount",
    "application/docbook+xml": "DocBook",
    "application/dssc+der":
        "Data Structure for the Security Suitability of Cryptographic Algorithms",
    "application/dssc+xml":
        "Data Structure for the Security Suitability of Cryptographic Algorithms",
    "application/ecmascript": "ECMAScript (IANA name)",
    "application/emma+xml": "Extensible MultiModal Annotation",
    "application/epub+zip": "Electronic Publication",
    "application/exi": "Efficient XML Interchange",
    "application/font-tdpfr": "Portable Font Resource",
    "application/gml+xml": "Geography Markup Language",
    "application/gpx+xml": "GPS Exchange Format",
    "application/gxf": "General eXchange Format",
    "application/hyperstudio": "Hyperstudio",
    "application/inkml+xml": "Ink Markup Language",
    "application/ipfix": "Internet Protocol Flow Information Export",
    "application/java-archive": "Java Archive",
    "application/java-serialized-object": "Java Serialized Object",
    "application/java-vm": "Java Bytecode File",
    "application/javascript": "JavaScript (IANA name)",
    "application/json": "JavaScript Object Notation (JSON)",
    "application/jsonml+json": "JSON Meta Application Language",
    "application/lost+xml": "Lost+xml",
    "application/mac-binhex40": "Macintosh BinHex 4.0",
    "application/mac-compactpro": "Compact Pro",
    "application/mads+xml": "Metadata Authority Description Schema",
    "application/marc": "MARC Formats",
    "application/marcxml+xml": "MARC21 XML Schema",
    "application/mathematica": "Mathematica Notebook Player",
    "application/mathml+xml": "Mathematical Markup Language",
    "application/mbox": "Mbox database files",
    "application/mediaservercontrol+xml":
        "Media Server Control Markup Language",
    "application/metalink+xml": "Metalink",
    "application/metalink4+xml": "Metalink",
    "application/mets+xml": "Metadata Encoding and Transmission Standard",
    "application/mods+xml": "Metadata Object Description Schema",
    "application/mp21": "MPEG-21",
    "application/mp4": "MPEG4",
    "application/msword": "Word (obsolete)",
    "application/mxf": "Material Exchange Format",
    "application/octet-stream": "Binary Data",
    "application/oda": "Office Document Architecture",
    "application/oebps-package+xml": "Open eBook Publication Structure",
    "application/ogg": "OGG",
    "application/omdoc+xml": "Open Mathematical Documents",
    "application/onenote": "OneNote",
    "application/oxps": "OpenXPS",
    "application/patch-ops-error+xml": "XML Patch Framework",
    "application/pdf": "PDF",
    "application/pgp-encrypted": "PGP Encrypted",
    "application/pgp-signature": "PGP Signature",
    "application/pics-rules": "Platform for Internet Content Selection (PICS)",
    "application/pkcs10": "PKCS #10 - Certification Request Standard",
    "application/pkcs7-mime": "Cryptographic Message Syntax",
    "application/pkcs7-signature": "Cryptographic Message Syntax",
    "application/pkcs8": "Private-Key Information Syntax Specification",
    "application/pkix-attr-cert": "Attribute Certificate",
    "application/pkix-cert": "Internet Public Key Infrastructure - Certificate",
    "application/pkix-crl":
        "Internet Public Key Infrastructure - Certificate Revocation Lists",
    "application/pkix-pkipath":
        "Internet Public Key Infrastructure - Certification Path",
    "application/pkixcmp":
        "Internet Public Key Infrastructure - Certificate Management Protocole",
    "application/pls+xml": "Media Playlist",
    "application/postscript": "PostScript",
    "application/prs.cww": "CU-Writer",
    "application/pskc+xml": "Portable Symmetric Key Container",
    "application/rdf+xml": "Resource Description Framework",
    "application/reginfo+xml": "IMS Global Learning Consortium",
    "application/relax-ng-compact-syntax": "RELAX NG",
    "application/resource-lists+xml": "Resource Lists",
    "application/resource-lists-diff+xml": "Resource Lists Diff",
    "application/rls-services+xml": "XML Resource Lists",
    "application/rpki-ghostbusters": "Relying Party",
    "application/rpki-manifest": "Manifest",
    "application/rpki-roa": "ROA",
    "application/rsd+xml": "RSD",
    "application/rss+xml": "RSS",
    "application/rtf": "Rich Text Format",
    "application/sbml+xml": "Systems Biology Markup Language",
    "application/scvp-cv-request":
        "Server-Based Certificate Validation Protocol - Validation Request",
    "application/scvp-cv-response":
        "Server-Based Certificate Validation Protocol - Validation Response",
    "application/scvp-vp-request":
        "Server-Based Certificate Validation Protocol - Validation Policies - Request",
    "application/scvp-vp-response":
        "Server-Based Certificate Validation Protocol - Validation Policies - Response",
    "application/sdp": "Session Description Protocol",
    "application/set-payment-initiation":
        "Secure Electronic Transaction - Payment",
    "application/set-registration-initiation":
        "Secure Electronic Transaction - Registration",
    "application/shf+xml": "Presentation Graphics",
    "application/smil+xml": "Synchronized Multimedia Integration Language",
    "application/sparql-query": "SPARQL - Query",
    "application/sparql-results+xml": "SPARQL - Results",
    "application/srgs": "Speech Recognition Grammar Specification",
    "application/srgs+xml": "Speech Recognition Grammar Specification - XML",
    "application/sru+xml": "Search/Retrieve via URL",
    "application/ssdl+xml": "Service Description",
    "application/ssml+xml": "Speech Synthesis Markup Language",
    "application/tei+xml": "Text Encoding and Interchange",
    "application/thraud+xml": "Digital Scriptorium",
    "application/timestamped-data": "Time Stamped Data Envelope",
    "application/vnd.3gpp.pic-bw-large":
        "3rd Generation Partnership Project - Pic Large",
    "application/vnd.3gpp.pic-bw-small":
        "3rd Generation Partnership Project - Pic Small",
    "application/vnd.3gpp.pic-bw-var":
        "3rd Generation Partnership Project - Pic Var",
    "application/vnd.3gpp2.tcap":
        "3rd Generation Partnership Project - Transaction Capabilities Application Part",
    "application/vnd.3m.post-it-notes": "3M Post It Notes",
    "application/vnd.accpac.simply.aso": "Simply Accounting",
    "application/vnd.accpac.simply.imp": "Simply Accounting - Data Import",
    "application/vnd.acucobol": "ACU Cobol",
    "application/vnd.acucorp": "ACU Cobol",
    "application/vnd.adobe.air-application-installer-package+zip":
        "Adobe AIR Application",
    "application/vnd.adobe.formscentral.fcdt": "Adobe FormsCentral",
    "application/vnd.adobe.fxp": "Adobe Flex Project",
    "application/vnd.adobe.xdp+xml": "Adobe XML Data Package",
    "application/vnd.adobe.xfdf": "Adobe XML Forms Data Format",
    "application/vnd.ahead.space": "Ahead AIR Application",
    "application/vnd.airzip.filesecure.azf": "AirZip FileSECURE",
    "application/vnd.airzip.filesecure.azs": "AirZip FileSECURE",
    "application/vnd.amazon.ebook": "Amazon Kindle eBook format",
    "application/vnd.americandynamics.acc": "Active Content Compression",
    "application/vnd.amiga.ami": "AmigaDE",
    "application/vnd.android.package-archive": "Android Package Archive",
    "application/vnd.anser-web-certificate-issue-initiation":
        "ANSER-WEB Terminal Client - Certificate Issue",
    "application/vnd.anser-web-funds-transfer-initiation":
        "ANSER-WEB Terminal Client - Web Funds Transfer",
    "application/vnd.antix.game-component": "Antix Game Player",
    "application/vnd.apple.installer+xml": "Apple Installer Package",
    "application/vnd.arastra.swi": "Arastra Swi",
    "application/vnd.ars.deployment-package": "Augmented Reality",
    "application/vnd.asa": "Asphalt Software",
    "application/vnd.astraea-software.iota": "Astraea Software",
    "application/vnd.audiograph": "Audiograph",
    "application/vnd.autopackage": "Auto Installer",
    "application/vnd.avistar+xml": "Avistar",
    "application/vnd.blueice.multipass": "Blueice Research Multipass",
    "application/vnd.bluetooth.ep.oob": "Bluetooth OOB",
    "application/vnd.bmi": "BMI Drawing Data Interchange",
    "application/vnd.businessobjects": "BusinessObjects",
    "application/vnd.cab-jscript": "Cabbage",
    "application/vnd.canon-cpdl": "Canon Digital Camera",
    "application/vnd.canon-lips": "Canon Digital Camera",
    "application/vnd.cendio.thinlinc.clientconf": "Cendio ThinLinc",
    "application/vnd.chemdraw+xml": "CambridgeSoft Chem Draw",
    "application/vnd.chipnuts.karaoke-mmd": "Chipnuts Karaoke",
    "application/vnd.cinderella": "Interactive Geometry Software",
    "application/vnd.cirpack.isdn-ext": "CIRPACK ISDN",
    "application/vnd.claymore": "Claymore Data Files",
    "application/vnd.cloanto.rp9": "Commodore 64 Preservation Project",
    "application/vnd.clonk.c4group": "Clonk Game",
    "application/vnd.cluetrust.cartomobile-config": "ClueTrust CartoMobile",
    "application/vnd.cluetrust.cartomobile-config-pkg": "ClueTrust CartoMobile",
    "application/vnd.collection+json": "Collection JSON",
    "application/vnd.commerce-battelle": "CommerceNet",
    "application/vnd.commonspace": "CommonSpace",
    "application/vnd.contact.cmsg": "Contact Management",
    "application/vnd.cosmocaller": "CosmoCaller",
    "application/vnd.crick.clicker": "Crick Software",
    "application/vnd.crick.clicker.keyboard": "Crick Software",
    "application/vnd.crick.clicker.palette": "Crick Software",
    "application/vnd.crick.clicker.template": "Crick Software",
    "application/vnd.crick.clicker.wordbank": "Crick Software",
    "application/vnd.criticaltools.wbs+xml": "Critical Tools",
    "application/vnd.ctc-posml": "CTC-Posml",
    "application/vnd.cups-ppd": "CUPS",
    "application/vnd.curl.car": "Curl - Applet",
    "application/vnd.curl.pcurl": "Curl - Pcurl",
    "application/vnd.dart": "Dart",
    "application/vnd.data-vision.rdz": "DataVision",
    "application/vnd.dece.data": "DECE Data",
    "application/vnd.dece.ttml+xml": "DECE TTA-Based Time",
    "application/vnd.dece.unspecified": "DECE Unspecified",
    "application/vnd.dece.zip": "DECE Zip",
    "application/vnd.denovo.fcselayout-link": "Denovo Fcselayout-Link",
    "application/vnd.dna": "DNA",
    "application/vnd.dolby.mlp": "Dolby Meridian Lossless Packing",
    "application/vnd.dpgraph": "DPGraph",
    "application/vnd.dreamfactory": "DreamFactory",
    "application/vnd.ds-keypoint": "Keys",
    "application/vnd.dvb.ait": "DVB",
    "application/vnd.dvb.service": "Digital Video Broadcasting",
    "application/vnd.dynageo": "Dynageo",
    "application/vnd.ecowin.chart": "EcoWin",
    "application/vnd.enliven": "Enliven Viewer",
    "application/vnd.epson.esf": "QUASS Stream Player",
    "application/vnd.epson.msf": "QUASS Stream Player",
    "application/vnd.epson.quickanime": "QUASS Stream Player",
    "application/vnd.epson.salt": "QUASS Stream Player",
    "application/vnd.epson.ssf": "QUASS Stream Player",
    "application/vnd.ericsson.quickcall": "Ericsson Quickcall",
    "application/vnd.eszigno3+xml": "Eszigno3",
    "application/vnd.eudora.data": "Eudora Data",
    "application/vnd.ezpix-album": "EZPix Secure Photo Album",
    "application/vnd.ezpix-package": "EZPix Secure Photo Album",
    "application/vnd.fdf": "Forms Data Format",
    "application/vnd.fdsn.mseed": "FDSN",
    "application/vnd.fdsn.seed": "FDSN",
    "application/vnd.flographit": "FloGraphIt",
    "application/vnd.fluxtime.clip": "FluxTime Clip",
    "application/vnd.framemaker": "Adobe FrameMaker",
    "application/vnd.frogans.fnc": "Frogans Player",
    "application/vnd.frogans.ltf": "Frogans Player",
    "application/vnd.fsc.weblaunch": "FS Craft Launch",
    "application/vnd.fujitsu.oasys": "Fujitsu Oasys",
    "application/vnd.fujitsu.oasys2": "Fujitsu Oasys",
    "application/vnd.fujitsu.oasys3": "Fujitsu Oasys",
    "application/vnd.fujitsu.oasysgp": "Fujitsu Oasys",
    "application/vnd.fujitsu.oasysprs": "Fujitsu Oasys",
    "application/vnd.fujixerox.ddd": "Fujitsu Multimedia Viewer",
    "application/vnd.fujixerox.docuworks": "Fujitsu Oasys",
    "application/vnd.fujixerox.docuworks.binder": "Fujitsu Oasys",
    "application/vnd.fuzzysheet": "FuzzySheet",
    "application/vnd.genomatix.tuxedo": "Genomatix Tuxedo Framework",
    "application/vnd.geogebra.file": "GeoGebra",
    "application/vnd.geogebra.tool": "GeoGebra",
    "application/vnd.geometry-explorer": "GEO",
    "application/vnd.geonext": "GEONExT and JSXGraph",
    "application/vnd.geoplan": "GeoplanW",
    "application/vnd.geospace": "GeospacW",
    "application/vnd.gmx": "GameMaker ActiveX",
    "application/vnd.google-earth.kml+xml": "Google Earth - KML",
    "application/vnd.google-earth.kmz": "Google Earth - KMZ",
    "application/vnd.grafeq": "GrafEq",
    "application/vnd.groove-account": "Groove - Account",
    "application/vnd.groove-help": "Groove - Help",
    "application/vnd.groove-identity-message": "Groove - Identity Message",
    "application/vnd.groove-injector": "Groove - Injector",
    "application/vnd.groove-tool-message": "Groove - Tool Message",
    "application/vnd.groove-tool-template": "Groove - Tool Template",
    "application/vnd.groove-vcard": "Groove - Vcard",
    "application/vnd.hal+xml": "Hal XML",
    "application/vnd.handheld-entertainment+xml": "ZVUE",
    "application/vnd.hbci": "Homebanking Computer Interface (HBCI)",
    "application/vnd.hhe.lesson-player": "Housecall",
    "application/vnd.hp-hpgl": "HP-GL/2 and HP RTL",
    "application/vnd.hp-pcl": "HP Printer Control Language",
    "application/vnd.hp-pclxl": "HP Printer Control Language",
    "application/vnd.hydrostatix.sof-data": "SOF",
    "application/vnd.hzn-3d-crossword": "3D Crossword Plugin",
    "application/vnd.ibm.minipay": "IBM Meme Media",
    "application/vnd.ibm.modcap": "MO:DCA-P",
    "application/vnd.ibm.rights-management": "IBM DB2 Rights Manager",
    "application/vnd.ibm.secure-container": "IBM DB2 Rights Manager",
    "application/vnd.iccprofile": "ICC profile",
    "application/vnd.igloader": "igLoader",
    "application/vnd.immervision-ivp": "ImmerVision PURE Players",
    "application/vnd.immervision-ivu": "ImmerVision PURE Players",
    "application/vnd.insors.igm": "iGrafx Professional",
    "application/vnd.intercon.formnet": "Intercon FormNet",
    "application/vnd.intergeo": "Interactive Geometry Software",
    "application/vnd.intu.qbo": "Quicken",
    "application/vnd.intu.qfx": "Quicken",
    "application/vnd.ipunplugged.rcprofile": "IP Unplugged",
    "application/vnd.irepository.package+xml": "iRepository / Lucidoc Editor",
    "application/vnd.is-xpr":
        "International Society for Advancement of Cytometry",
    "application/vnd.isac.fcs": "Flow Cytometry Standard",
    "application/vnd.jam": "Jam STAPL",
    "application/vnd.jcp.javame.midlet-rms":
        "Mobile Information Device Profile",
    "application/vnd.jisp": "RhymBox",
    "application/vnd.joost.joda-archive": "Joda Archive",
    "application/vnd.kahootz": "Kahootz",
    "application/vnd.kde.karbon": "KDE KOffice Office Suite - Karbon",
    "application/vnd.kde.kchart": "KDE KOffice Office Suite - KChart",
    "application/vnd.kde.kformula": "KDE KOffice Office Suite - KFormula",
    "application/vnd.kde.kivio": "KDE KOffice Office Suite - Kivio",
    "application/vnd.kde.kontour": "KDE KOffice Office Suite - Kontour",
    "application/vnd.kde.kpresenter": "KDE KOffice Office Suite - KPresenter",
    "application/vnd.kde.kspread": "KDE KOffice Office Suite - KSpread",
    "application/vnd.kde.kword": "KDE KOffice Office Suite - KWord",
    "application/vnd.kenameaapp": "Kenamea App",
    "application/vnd.kidspiration": "Kidspiration",
    "application/vnd.kinar": "Kinar Applications",
    "application/vnd.koan": "Koan Interactive Fiction",
    "application/vnd.kodak-descriptor": "Kodak Storyshare",
    "application/vnd.las.las+xml": "LAS VEGAS",
    "application/vnd.llamagraphics.life-balance.desktop": "Life Balance",
    "application/vnd.llamagraphics.life-balance.exchange+xml": "Life Balance",
    "application/vnd.lotus-1-2-3": "Lotus 1-2-3",
    "application/vnd.lotus-approach": "Lotus Approach",
    "application/vnd.lotus-freelance": "Lotus Freelance",
    "application/vnd.lotus-notes": "Lotus Notes",
    "application/vnd.lotus-organizer": "Lotus Organizer",
    "application/vnd.lotus-screencam": "Lotus Screencam",
    "application/vnd.lotus-wordpro": "Lotus Wordpro",
    "application/vnd.macports.portpkg": "MacPorts Port System",
    "application/vnd.mcd": "Micro CADAM Helix D&D",
    "application/vnd.medcalcdata": "MedCalc",
    "application/vnd.mediastation.cdkey": "MediaRemote",
    "application/vnd.mfer": "Medical Waveform Encoding Format",
    "application/vnd.mfmp": "Melody Format for Mobile Platform",
    "application/vnd.micrografx.flo": "Micrografx",
    "application/vnd.micrografx.igx": "Micrografx",
    "application/vnd.mif": "FrameMaker Interchange Format",
    "application/vnd.mobius.daf":
        "Mobius Management Systems - UniversalArchive",
    "application/vnd.mobius.dis":
        "Mobius Management Systems - Distribution Database",
    "application/vnd.mobius.mbk": "Mobius Management Systems - Basket file",
    "application/vnd.mobius.mqy": "Mobius Management Systems - Query File",
    "application/vnd.mobius.msl":
        "Mobius Management Systems - Policy Definition Language File",
    "application/vnd.mobius.plc":
        "Mobius Management Systems - Planimeter Document",
    "application/vnd.mobius.txf":
        "Mobius Management Systems - Topic Index File",
    "application/vnd.mophun.application": "Mophun VM",
    "application/vnd.mophun.certificate": "Mophun VM",
    "application/vnd.mozilla.xul+xml": "Mozilla XUL",
    "application/vnd.ms-artgalry": "Artgalry",
    "application/vnd.ms-cab-compressed": "Cabinet File",
    "application/vnd.ms-excel": "Excel (deprecated)",
    "application/vnd.ms-excel.addin.macroenabled.12":
        "Excel - Add-In File (macroenabled)",
    "application/vnd.ms-excel.sheet.binary.macroenabled.12":
        "Excel - Binary Workbook (macroenabled)",
    "application/vnd.ms-excel.sheet.macroenabled.12":
        "Excel - Macro-Enabled Workbook",
    "application/vnd.ms-excel.template.macroenabled.12":
        "Excel - Macro-Enabled Template File",
    "application/vnd.ms-fontobject": "Embedded OpenType",
    "application/vnd.ms-htmlhelp": "Html Help File",
    "application/vnd.ms-ims": "Class Server",
    "application/vnd.ms-lrm": "Learning Resource Module",
    "application/vnd.ms-office.activex+xml": "Office - ActiveX",
    "application/vnd.ms-officetheme": "Office System Release Theme",
    "application/vnd.ms-playready.initiator+xml": "PlayReady Ecosystem",
    "application/vnd.ms-powerpoint": "PowerPoint (deprecated)",
    "application/vnd.ms-powerpoint.addin.macroenabled.12":
        "PowerPoint - Add-in file (macroenabled)",
    "application/vnd.ms-powerpoint.presentation.macroenabled.12":
        "PowerPoint - Macro-Enabled Presentation File",
    "application/vnd.ms-powerpoint.slide.macroenabled.12":
        "PowerPoint - Macro-Enabled Slide File",
    "application/vnd.ms-powerpoint.slideshow.macroenabled.12":
        "PowerPoint - Macro-Enabled Slide Show File",
    "application/vnd.ms-powerpoint.template.macroenabled.12":
        "PowerPoint - Macro-Enabled Template File",
    "application/vnd.ms-project": "Project (deprecated)",
    "application/vnd.ms-word.document.macroenabled.12":
        "Word - Macro-Enabled Document",
    "application/vnd.ms-word.template.macroenabled.12":
        "Word - Macro-Enabled Template",
    "application/vnd.ms-works": "Works",
    "application/vnd.ms-wpl": "Windows Media Player Playlist",
    "application/vnd.ms-xpsdocument": "XML Paper Specification",
    "application/vnd.mseq": "MSEQ",
    "application/vnd.musician":
        "MUsical Score Interpreted Code Invented for the ASCII designation of Notation",
    "application/vnd.muvee.style": "Muvee Automatic Video Editing",
    "application/vnd.mynfc": "MyNFC",
    "application/vnd.neurolanguage.nlu": "NeuroLanguage",
    "application/vnd.nitf": "News Industry Text Format",
    "application/vnd.noblenet-directory": "NobleNet Directory",
    "application/vnd.noblenet-sealer": "NobleNet Sealer",
    "application/vnd.noblenet-web": "NobleNet Web",
    "application/vnd.nokia.n-gage.data": "N-Gage Game Data",
    "application/vnd.nokia.radio-preset": "Nokia Radio Application - Preset",
    "application/vnd.nokia.radio-presets": "Nokia Radio Application - Preset",
    "application/vnd.novadigm.edm": "Novadigm",
    "application/vnd.novadigm.edx": "Novadigm",
    "application/vnd.novadigm.ext": "Novadigm",
    "application/vnd.oasis.opendocument.chart": "OpenDocument Chart",
    "application/vnd.oasis.opendocument.chart-template":
        "OpenDocument Chart Template",
    "application/vnd.oasis.opendocument.database": "OpenDocument Database",
    "application/vnd.oasis.opendocument.formula": "OpenDocument Formula",
    "application/vnd.oasis.opendocument.formula-template":
        "OpenDocument Formula Template",
    "application/vnd.oasis.opendocument.graphics": "OpenDocument Graphics",
    "application/vnd.oasis.opendocument.graphics-template":
        "OpenDocument Graphics Template",
    "application/vnd.oasis.opendocument.image": "OpenDocument Image",
    "application/vnd.oasis.opendocument.image-template":
        "OpenDocument Image Template",
    "application/vnd.oasis.opendocument.presentation":
        "OpenDocument Presentation",
    "application/vnd.oasis.opendocument.presentation-template":
        "OpenDocument Presentation Template",
    "application/vnd.oasis.opendocument.spreadsheet":
        "OpenDocument Spreadsheet",
    "application/vnd.oasis.opendocument.spreadsheet-template":
        "OpenDocument Spreadsheet Template",
    "application/vnd.oasis.opendocument.text": "OpenDocument Text",
    "application/vnd.oasis.opendocument.text-master":
        "OpenDocument Text Master",
    "application/vnd.oasis.opendocument.text-template":
        "OpenDocument Text Template",
    "application/vnd.oasis.opendocument.text-web": "OpenDocument Text Web",
    "application/vnd.olpc-sugar": "Sugar Linux Application Bundle",
    "application/vnd.oma.dd2+xml": "OMA Download Agents",
    "application/vnd.openofficeorg.extension": "Open Office Extension",
    "application/vnd.openxmlformats-officedocument.presentationml.presentation":
        "PowerPoint",
    "application/vnd.openxmlformats-officedocument.presentationml.slide":
        "PowerPoint",
    "application/vnd.openxmlformats-officedocument.presentationml.slideshow":
        "PowerPoint",
    "application/vnd.openxmlformats-officedocument.presentationml.template":
        "PowerPoint",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet":
        "Excel",
    "application/vnd.openxmlformats-officedocument.spreadsheetml.template":
        "Excel",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document":
        "Word",
    "application/vnd.openxmlformats-officedocument.wordprocessingml.template":
        "Word",
    "application/vnd.osgeo.mapguide.package": "MapGuide DBXML",
    "application/vnd.osgi.dp": "OSGi Deployment Package",
    "application/vnd.osgi.subsystem": "OSGi Deployment Package",
    "application/vnd.palm": "PalmOS Data",
    "application/vnd.pawaafile": "PawaaFILE",
    "application/vnd.pg.format": "PGP Desktop",
    "application/vnd.pg.osasli": "PGP Desktop",
    "application/vnd.picsel": "Pcsel eFIF File",
    "application/vnd.pmi.widget": "Qualcomm Package",
    "application/vnd.pocketlearn": "PocketLearn Viewers",
    "application/vnd.powerbuilder6": "PowerBuilder",
    "application/vnd.previewsystems.box": "Preview Systems ZipLock/VBox",
    "application/vnd.proteus.magazine": "Proteus",
    "application/vnd.publishare-delta-tree": "Publishare Applications",
    "application/vnd.pvi.ptid1": "Princeton Video Image",
    "application/vnd.quark.quarkxpress": "QuarkXpress",
    "application/vnd.realvnc.bed": "RealVNC",
    "application/vnd.recordare.musicxml": "Recordare Applications",
    "application/vnd.recordare.musicxml+xml": "Recordare Applications",
    "application/vnd.rig.cryptonote": "Rig",
    "application/vnd.rim.cod": "Blackberry COD File",
    "application/vnd.rn-realmedia": "RealMedia",
    "application/vnd.route66.link66+xml": "ROUTE 66 Location Based Services",
    "application/vnd.sailingtracker.track": "SailingTracker",
    "application/vnd.seemail": "SeeMail",
    "application/vnd.sema": "Secured eMail",
    "application/vnd.semd": "Secured eMail",
    "application/vnd.semf": "Secured eMail",
    "application/vnd.shana.informed.formdata": "Shana Informed Filler",
    "application/vnd.shana.informed.formtemplate": "Shana Informed Filler",
    "application/vnd.shana.informed.interchange": "Shana Informed Filler",
    "application/vnd.shana.informed.package": "Shana Informed Filler",
    "application/vnd.simtech-mindmapper": "SimTech MindMapper",
    "application/vnd.smaf": "Mobile Music Polyphonic",
    "application/vnd.smart.teacher": "SMART Technologies Apps",
    "application/vnd.solent.sdkm+xml": "Solent SDKM",
    "application/vnd.spotfire.dxp": "TIBCO Spotfire",
    "application/vnd.spotfire.sfs": "TIBCO Spotfire",
    "application/vnd.stardivision.calc": "StarOffice - Calc",
    "application/vnd.stardivision.draw": "StarOffice - Draw",
    "application/vnd.stardivision.impress": "StarOffice - Impress",
    "application/vnd.stardivision.math": "StarOffice - Math",
    "application/vnd.stardivision.writer": "StarOffice - Writer",
    "application/vnd.stardivision.writer-global":
        "StarOffice - Writer (Global)",
    "application/vnd.stepmania.package": "StepMania",
    "application/vnd.stepmania.stepchart": "StepMania",
    "application/vnd.sun.xml.calc": "OpenOffice - Calc (Spreadsheet)",
    "application/vnd.sun.xml.calc.template":
        "OpenOffice - Calc Template (Spreadsheet)",
    "application/vnd.sun.xml.draw": "OpenOffice - Draw (Graphics)",
    "application/vnd.sun.xml.draw.template":
        "OpenOffice - Draw Template (Graphics)",
    "application/vnd.sun.xml.impress": "OpenOffice - Impress (Presentation)",
    "application/vnd.sun.xml.impress.template":
        "OpenOffice - Impress Template (Presentation)",
    "application/vnd.sun.xml.math": "OpenOffice - Math (Formula)",
    "application/vnd.sun.xml.writer": "OpenOffice - Writer (Text - HTML)",
    "application/vnd.sun.xml.writer.global":
        "OpenOffice - Writer (Text - HTML)",
    "application/vnd.sun.xml.writer.template":
        "OpenOffice - Writer Template (Text - HTML)",
    "application/vnd.sus-calendar": "ScheduleUs",
    "application/vnd.svd": "SVD",
    "application/vnd.symbian.install": "Symbian Install Package",
    "application/vnd.syncml+xml": "SyncML",
    "application/vnd.syncml.dm+wbxml": "SyncML - Device Management",
    "application/vnd.syncml.dm+xml": "SyncML - Device Management",
    "application/vnd.tao.intent-module-archive": "Intent Engine",
    "application/vnd.tcpdump.pcap": "Tcpdump",
    "application/vnd.tmobile-livetv": "T-Mobile",
    "application/vnd.trid.tpt": "TRI Systems",
    "application/vnd.triscape.mxs": "Triscape Map Explorer",
    "application/vnd.trueapp": "True BASIC",
    "application/vnd.ufdl": "Universal Forms Description Language",
    "application/vnd.uiq.theme": "User Interface Quartz",
    "application/vnd.umajin": "UMAJIN",
    "application/vnd.unity": "Unity 3d",
    "application/vnd.uoml+xml": "Unique Object Markup Language",
    "application/vnd.vcx": "VirtualCatalog",
    "application/vnd.visio": "Visio",
    "application/vnd.visionary": "Visionary",
    "application/vnd.vsf": "Viewport+",
    "application/vnd.wap.wbxml": "WAP Binary XML (WBXML)",
    "application/vnd.wap.wmlc": "WAP Binary XML (WBXML)",
    "application/vnd.wap.wmlscriptc": "WAP Binary XML (WBXML)",
    "application/vnd.webturbo": "WebTurbo",
    "application/vnd.wolfram.player": "Mathematica Notebook Player",
    "application/vnd.wordperfect": "WordPerfect",
    "application/vnd.wqd": "World Wide Web Consortium",
    "application/vnd.wt.stf": "Worldtalk",
    "application/vnd.xara": "Xara",
    "application/vnd.xfdl": "Extensible Forms Description Language",
    "application/vnd.yamaha.hv-dic": "HV Voice Dictionary",
    "application/vnd.yamaha.hv-script": "HV Script",
    "application/vnd.yamaha.hv-voice": "HV Voice Parameter",
    "application/vnd.yamaha.openscoreformat": "Open Score Format",
    "application/vnd.yamaha.openscoreformat.osfpvg+xml": "Open Score Format",
    "application/vnd.yamaha.smaf-audio": "SMAF Audio",
    "application/vnd.yamaha.smaf-phrase": "SMAF Phrase",
    "application/vnd.yamaha.through-ngn": "Through Ngn",
    "application/vnd.yamaha.tunnel-udpencap": "Tunnel UDP",
    "application/vnd.yellowriver-custom-menu": "Yellow River Custom Menu",
    "application/vnd.zul": "Z.U.L. Geometry",
    "application/vnd.zzazz.deck+xml": "Zzazz Deck",
    "application/voicexml+xml": "VoiceXML",
    "application/widget": "Widget Packaging and XML Configuration",
    "application/winhlp": "WinHelp",
    "application/wsdl+xml": "Web Services Description Language",
    "application/wspolicy+xml": "Web Services Policy",
    "application/x-7z-compressed": "7-Zip",
    "application/x-abiword": "AbiWord",
    "application/x-ace-compressed": "Ace Archive",
    "application/x-apple-diskimage": "Apple Disk Image",
    "application/x-authorware-bin": "Authorware",
    "application/x-authorware-map": "Authorware",
    "application/x-authorware-seg": "Authorware",
    "application/x-bcpio": "Binary CPIO Archive",
    "application/x-bittorrent": "BitTorrent",
    "application/x-blorb": "Blorb Game",
    "application/x-bzip": "Bzip Archive",
    "application/x-bzip2": "Bzip2 Archive",
    "application/x-cbr": "Comic Book Archive",
    "application/x-cdlink": "CD-ROM XA",
    "application/x-cfs-compressed": "Compact File Set",
    "application/x-chat": "pIRCh",
    "application/x-chess-pgn": "Portable Game Notation (Chess Games)",
    "application/x-conference": "CoolTalk",
    "application/x-cpio": "CPIO Archive",
    "application/x-csh": "C Shell Script",
    "application/x-debian-package": "Debian Package",
    "application/x-dgc-compressed": "DGC Compressed Archive",
    "application/x-director": "Adobe Director",
    "application/x-doom": "DOOM",
    "application/x-dtbncx+xml": "EPUB Navigation Control XML",
    "application/x-dtbook+xml": "EPUB Digital Talking Book",
    "application/x-dtbresource+xml": "EPUB Resource File",
    "application/x-dvi": "DVI",
    "application/x-envoy": "Envoy",
    "application/x-eva": "EVA",
    "application/x-font-bdf": "Glyph Bitmap Distribution Format",
    "application/x-font-ghostscript": "PostScript Fonts",
    "application/x-font-linux-psf": "PSF Fonts",
    "application/x-font-otf": "OpenType Font",
    "application/x-font-pcf": "Portable Compiled Format",
    "application/x-font-snf": "Server Normal Format",
    "application/x-font-ttf": "TrueType Font",
    "application/x-font-type1": "PostScript Type 1 Font",
    "application/x-font-woff": "Web Open Font Format",
    "application/x-freearc": "FreeArc Archive",
    "application/x-futuresplash": "FutureSplash Animator",
    "application/x-gca-compressed": "GCA Compressed Archive",
    "application/x-glulx": "Glulx Interactive Fiction",
    "application/x-gnumeric": "Gnumeric Spreadsheet",
    "application/x-gramps-xml": "Gramps XML Genealogy",
    "application/x-gtar": "GNU Tar Archive",
    "application/x-hdf": "Hierarchical Data Format",
    "application/x-install-instructions": "InstallShield",
    "application/x-iso9660-image": "ISO Disk Image",
    "application/x-java-jnlp-file": "Java Network Launch Protocol",
    "application/x-latex": "LaTeX",
    "application/x-lzh-compressed": "LHA/LZH Compressed Archive",
    "application/x-mie": "MIE",
    "application/x-mobipocket-ebook": "Mobipocket",
    "application/x-ms-application": "MS Application",
    "application/x-ms-shortcut": "Shortcut",
    "application/x-ms-wmd": "Windows Media Player Download Package",
    "application/x-ms-wmz": "Windows Media Player Skin Package",
    "application/x-ms-xbap": "XBAP",
    "application/x-msaccess": "Access",
    "application/x-msbinder": "Binder",
    "application/x-mscardfile": "Cardfile",
    "application/x-msclip": "Clip Gallery Live Clipboard",
    "application/x-msdos-program": "MS-DOS Application",
    "application/x-msdownload": "Download",
    "application/x-msmediaview": "MediaView",
    "application/x-msmetafile": "Metafile",
    "application/x-msmoney": "Money",
    "application/x-mspublisher": "Publisher",
    "application/x-msschedule": "Schedule Plus",
    "application/x-msterminal": "Terminal Services",
    "application/x-mswrite": "WordPad",
    "application/x-netcdf": "Network Common Data Form (NetCDF)",
    "application/x-nzb": "NewzBin Usenet Index File",
    "application/x-pkcs12": "Personal Information Exchange Syntax Standard",
    "application/x-pkcs7-certificates":
        "PKCS #7 - Cryptographic Message Syntax Standard (Certificates)",
    "application/x-pkcs7-certreqresp":
        "PKCS #7 - Cryptographic Message Syntax Standard (Certificate Request Response)",
    "application/x-rar-compressed": "RAR Archive",
    "application/x-research-info-systems": "Research InfoSystems",
    "application/x-sh": "Bourne Shell Script",
    "application/x-shar": "Shell Archive",
    "application/x-shockwave-flash": "Adobe Flash",
    "application/x-silverlight-app": "Silverlight",
    "application/x-sql": "SQL",
    "application/x-stuffit": "StuffIt Archive",
    "application/x-stuffitx": "StuffIt X Archive",
    "application/x-subrip": "SubRip Subtitle",
    "application/x-sv4cpio": "System V Release 4 CPIO Archive",
    "application/x-sv4crc": "System V Release 4 CRC",
    "application/x-t3vm-image": "T3vm Image",
    "application/x-tads": "TADS",
    "application/x-tar": "Tar File",
    "application/x-tcl": "Tcl Script",
    "application/x-tex": "TeX",
    "application/x-tex-tfm": "TeX Font Metric",
    "application/x-texinfo": "GNU Texinfo Document",
    "application/x-tgif": "Tgif",
    "application/x-ustar": "Ustar Archive",
    "application/x-wais-source": "WAIS Source",
    "application/x-web-app-manifest+json": "Web App Manifest",
    "application/x-x509-ca-cert": "X.509 Certificate",
    "application/x-xfig": "Xfig",
    "application/x-xliff+xml":
        "XLIFF (XML Localization Interchange File Format)",
    "application/x-xpinstall": "XPInstall",
    "application/x-xz": "XZ Archive",
    "application/x-zmachine": "Z-machine",
    "application/xaml+xml": "XAML",
    "application/xcap-diff+xml": "XCAP Diff",
    "application/xenc+xml": "XML Encryption Syntax and Processing",
    "application/xhtml+xml": "XHTML",
    "application/xml": "XML - Extensible Markup Language",
    "application/xml-dtd": "DTD",
    "application/xop+xml": "XOP - XML-binary Optimized Packaging",
    "application/xproc+xml": "XProc - XML Pipeline Language",
    "application/xslt+xml": "XSLT - XML Stylesheet Language Transformation",
    "application/xspf+xml": "XSPF - XML Shareable Playlist Format",
    "application/xv+xml": "MXML",
    "application/yang": "YANG Data Modeling Language",
    "application/yin+xml": "YIN (YANG - XML)",
    "application/zip": "ZIP Archive",
    "application/ccmp+xml": "CCMP",
    "application/applefile": "Apple File",
    "application/auth-policy+xml": "Authorization Policy",
    "application/batch-smtp": "Batch SMTP",
    "application/beep+xml": "Beep",
    "application/calendar+xml": "Calendar",
    "application/call-completion": "Call Completion",
    "application/cals-1840": "CALS",
    "application/cea": "CEA",
    "application/cellml+xml": "CellML",
    "application/cfw": "CFW",
    "application/cnrp+xml": "CNR",
    "application/commonground": "Common Ground",
    "application/conference-info+xml": "Conference Info",
    "application/cpl+xml": "CPL",
    "application/csrattrs": "CSR",
    "application/cybercash": "CyberCash",
    "application/dca-rft": "DCA RFT",
    "application/dec-dx": "DEC DX",
    "application/dialog-info+xml": "Dialog Info",
    "application/dicom": "DICOM",
    "application/dii": "DII",
    "application/dns": "DNS",
    "application/dskpp+xml": "DSKPP",
    "application/dvcs": "DVCS",
    "application/edi-consent": "EDI Consent",
    "application/edi-x12": "EDI X12",
    "application/edifact": "EDIFACT",
    "application/efi": "EFI",
    "application/emergencycalldata.comment+xml": "EmergencyCallData.Comment",
    "application/emergencycalldata.deviceinfo+xml":
        "EmergencyCallData.DeviceInfo",
    "application/emergencycalldata.providerinfo+xml":
        "EmergencyCallData.ProviderInfo",
    "application/emergencycalldata.serviceinfo+xml":
        "EmergencyCallData.ServiceInfo",
    "application/emergencycalldata.subscriberinfo+xml":
        "EmergencyCallData.SubscriberInfo",
    "application/epp+xml": "EPP",
    "application/eshop": "ESHOP",
    "application/example": "Example",
    "application/fastinfoset": "Fast Infoset",
    "application/fastsoap": "Fast SOAP",
    "application/fits": "FITS",
    "application/font-sfnt": "Font SFNT",
    "application/font-woff": "Font WOFF",
    "application/framework-attributes+xml": "Framework Attributes",
    "application/h224": "H.224",
    "application/hip": "HIP",
    "application/held+xml": "HELD",
    "application/http": "HTTP",
    "application/ibe-key-request+xml": "IBE Key Request",
    "application/ibe-pkg-reply+xml": "IBE Package Reply",
    "application/ibe-pp-data": "IBE PP Data",
    "application/iges": "IGES",
    "application/im-iscomposing+xml": "IM Composing",
    "application/index": "Index",
    "application/index.cmd": "Index CMD",
    "application/index.obj": "Index OBJ",
    "application/index.response": "Index Response",
    "application/index.vnd": "Index VND",
    "application/ipp": "IPP",
    "application/isup": "ISUP",
    "application/jose": "JOSE",
    "application/jose+json": "JOSE JSON",
    "application/json-patch+json": "JSON Patch",
    "application/json-seq": "JSON Sequence",
    "application/jwk+json": "JWK JSON",
    "application/jwk-set+json": "JWK Set JSON",
    "application/jwt": "JWT",
    "application/kpml-request+xml": "KPML Request",
    "application/kpml-response+xml": "KPML Response",
    "application/ld+json": "JSON-LD",
    "application/link-format": "Link Format",
    "application/load-control+xml": "Load Control",
    "application/lostsync+xml": "LOSTSYNC",
    "application/lxf": "LXF",
    "application/macwriteii": "MacWriteII",
    "application/media_control+xml": "Media Control",
    "application/mikey": "MIKEY",
    "application/moss-keys": "MOSS Keys",
    "application/moss-signature": "MOSS Signature",
    "application/mosskey-data": "MOSSKey Data",
    "application/mosskey-request": "MOSSKey Request",
    "application/mpeg4-generic": "MPEG-4 Generic",
    "application/mpeg4-iod": "MPEG4 IOD",
    "application/msc-ivr+xml": "MSC IVR",
    "application/msc-mixer+xml": "MSC Mixer",
    "application/nasdata": "NAS Data",
    "application/news-checkgroups": "News Checkgroups",
    "application/news-groupinfo": "News Groupinfo",
    "application/news-transmission": "News Transmission",
    "application/nss": "NSS",
    "application/ocsp-request": "OCSP Request",
    "application/ocsp-response": "OCSP Response",
    "application/p2p-overlay+xml": "P2P Overlay",
    "application/parityfec": "Parity FEC",
    "application/pgp-keys": "PGP Keys",
    "application/pidf+xml": "PIDF",
    "application/pidf-diff+xml": "PIDF Diff",
    "application/pkcs12": "PKCS#12",
    "application/pkcs8-encrypted": "PKCS#8 Encrypted",
    "application/provenance+xml": "Provenance",
}

export const textMimeTypes: { [key: string]: string } = {
    "text/1d-interleaved-parityfec": "1D Interleaved Parity FEC",
    "text/cache-manifest": "Cache Manifest",
    "text/calendar": "Calendar",
    "text/css": "CSS",
    "text/csv": "CSV",
    "text/csv-schema": "CSV Schema",
    "text/directory": "Directory",
    "text/dns": "DNS",
    "text/ecmascript": "ECMAScript",
    "text/encaprtp": "Encapsulated RTP",
    "text/enriched": "Enriched",
    "text/fwdred": "Forwarded",
    "text/grammar-ref-list": "Grammar Ref List",
    "text/html": "HTML",
    "text/javascript": "JavaScript",
    "text/markdown": "Markdown",
    "text/mizar": "Mizar",
    "text/n3": "N3",
    "text/parameters": "Parameters",
    "text/plain": "Text",
    "text/provenance-notation": "Provenance Notation",
    "text/prs.fallenstein.rst": "PRS",
    "text/prs.lines.tag": "Lines Tag",
    "text/rfc822-headers": "RFC 822 Headers",
    "text/richtext": "Rich Text Format (RTF)",
    "text/rtf": "RTF",
    "text/rtp-enc-aescm128": "RTP Enc AESCM128",
    "text/rtploopback": "Loopback",
    "text/rtx": "RTX",
    "text/sgml": "SGML",
    "text/t140": "T140",
    "text/tab-separated-values": "Tab Separated Values",
    "text/troff": "Troff",
    "text/turtle": "Turtle",
    "text/ulpfec": "ULP FEC",
    "text/uri-list": "URI List",
    "text/vcard": "vCard",
    "text/vnd.a": "A",
    "text/vnd.abc": "ABC",
    "text/vnd.curl": "Curl",
    "text/vnd.dmclientscript": "DMClient Script",
    "text/vnd.dvb.subtitle": "DVB Subtitle",
    "text/vnd.esmertec.theme-descriptor": "ESM",
    "text/vnd.fly": "Fly",
    "text/vnd.fmi.flexstor": "Flexstor",
    "text/vnd.graphviz": "Graphviz",
    "text/vnd.in3d.3dml": "3DML",
    "text/vnd.in3d.spot": "3D Spot",
    "text/vnd.iptc.newsml": "IPTC NewsML",
    "text/vnd.iptc.nitf": "IPTC NITF",
    "text/vnd.latex-z": "Latex Z",
    "text/vnd.motorola.reflex": "Motorola Reflex",
    "text/vnd.ms-mediapackage": "Media Package",
    "text/vnd.net2phone.commcenter.command": "Commcenter Command",
    "text/vnd.radisys.msml-basic-layout": "MSML",
    "text/vnd.si.uricatalogue": "SURI Catalogue",
    "text/vnd.sun.j2me.app-descriptor": "J2ME App Descriptor",
    "text/vnd.trolltech.linguist": "Linguist",
    "text/vnd.wap.si": "Wireless",
    "text/vnd.wap.sl": "Service Load",
    "text/vnd.wap.wml": "WML",
    "text/vnd.wap.wmlscript": "WMLScript",
    "text/vtt": "VTT",
    "text/x-asm": "Assembly",
    "text/x-c": "C",
    "text/x-component": "Component",
    "text/x-fortran": "Fortran",
    "text/x-handlebars-template": "Handlebars Template",
    "text/x-java-source": "Java Source",
    "text/x-lua": "Lua",
    "text/x-markdown": "Markdown",
    "text/x-nfo": "NFO",
    "text/x-opml": "OPML",
    "text/x-pascal": "Pascal",
    "text/x-processing": "Processing",
    "text/x-sfv": "SFV",
    "text/x-suse-ymp": "SUSE YMP",
    "text/x-uuencode": "UUencode",
    "text/x-vcalendar": "vCalendar",
    "text/x-vcard": "vCard",
    "text/xml": "XML",
    "text/xml-external-parsed-entity": "XML External Parsed Entity",
    "text/yaml": "YAML",
    "text/x-log": "Log",
}

export const otherMimeTypes: { [key: string]: string } = {
    "chemical/x-xyz": "XYZ File Format",
    "message/cpim": "CPIM",
    "message/delivery-status": "Delivery Status",
    "message/disposition-notification": "Disposition Notification",
    "message/external-body": "External Body",
    "message/feedback-report": "Feedback Report",
    "message/global": "Global",
    "message/global-delivery-status": "Global Delivery Status",
    "message/global-disposition-notification":
        "Global Disposition Notification",
    "message/global-headers": "Global Headers",
    "message/http": "HTTP",
    "message/imdn+xml": "IMDN",
    "message/news": "News Message",
    "message/partial": "Partial Message",
    "message/rfc822": "RFC 822",
    "message/s-http": "Secure HTTP",
    "message/sip": "Session Initiation Protocol (SIP)",
    "message/sipfrag": "SIP Fragment",
    "message/tracking-status": "Tracking Status",
    "message/vnd.si.simp": "SIMP",
    "message/vnd.wfa.wsc": "Wireless",
    "model/iges": "Initial Graphics Exchange Specification (IGES)",
    "model/mesh": "Mesh Data Type",
    "model/vnd.collada+xml": "COLLADA",
    "model/vnd.dwf": "DWF Drawing",
    "model/vnd.flatland.3dml": "Flatland",
    "model/vnd.gdl": "Geometric",
    "model/vnd.gs-gdl": "GS",
    "model/vnd.gtw": "GTW",
    "model/vnd.moml+xml": "MOML",
    "model/vnd.mts": "MTS",
    "model/vnd.parasolid.transmit.binary": "Parasolid",
    "model/vnd.parasolid.transmit.text": "Parasolid",
    "model/vnd.vtu": "VTU",
    "model/vrml": "VRML",
    "model/x3d+binary": "X3D Binary",
    "model/x3d+vrml": "X3D VRML",
    "model/x3d+xml": "X3D",
    "multipart/alternative": "Alternative",
    "multipart/appledouble": "Appledouble",
    "multipart/byteranges": "Byte Ranges",
    "multipart/digest": "Digest",
    "multipart/encrypted": "Encrypted",
    "multipart/form-data": "Form Data",
    "multipart/header-set": "Header Set",
    "multipart/mixed": "Mixed",
    "multipart/parallel": "Parallel",
    "multipart/related": "Related",
    "multipart/report": "Report",
    "multipart/signed": "Signed",
    "multipart/voice-message": "Voice Message",
    "x-conference/x-cooltalk": "CoolTalk",
}

// Images
export const missingImage =
    require("@zendeskgarden/svg-icons/src/16/file-image-stroke.svg")
        .default as string

export const overFlowImage =
    require("@zendeskgarden/svg-icons/src/16/align-justify-stroke.svg")
        .default as string

export const documentIcon =
    require("@zendeskgarden/svg-icons/src/16/file-document-stroke.svg")
        .default as string

export const pdfIcon =
    require("@zendeskgarden/svg-icons/src/16/file-pdf-stroke.svg")
        .default as string

export const genericIcon =
    require("@zendeskgarden/svg-icons/src/16/file-generic-stroke.svg")
        .default as string

export const zipIcon =
    require("@zendeskgarden/svg-icons/src/16/file-zip-stroke.svg")
        .default as string
